# vi net-pol-allow-port-8080-in-same-namespace-for-all-pods.yaml

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prod-net-policy1
  namespace: prod
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
     - from:
          - namespaceSelector:
               matchLabels:
                    area: prod
            podSelector: {}
       ports:
        - protocol: TCP
          port: 8080

